### PR TITLE
Optionally return more detailed exception messages when SQL statements fail

### PR DESCRIPTION
**Pull request by DavidGregory084**
@p14n @kutchar I'm interested in your opinions on this one

### CODE REVIEW

**Comment by kutchar** [comment]
@DavidGregory084 I like it!

**Comment by DavidGregory084** [comment]
Yep, that sounds reasonable to me 👍

**Comment by kutchar** [comment]
What would be even better if we added a sql exception translation layer, similar to [Spring DAO](https://github.com/spring-projects/spring-framework/tree/master/spring-tx/src/main/java/org/springframework/dao) instead of only returning SqlestExceptions

**Comment by DavidGregory084** [comment]
I'm going to merge this as-is as I don't think I will have a chance to look at error code mappings any time soon, hope that's ok

**Pull request merged**
